name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - run: yarn run lint:eslint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - run: yarn run lint:prettier

  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.3.4

  codegen:
    name: Codegen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - run: yarn run generate:codegen
      - run: test -z "$(git diff --name-only | grep schema.graphql)" ; exit $?

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - run: yarn run generate
      - run: yarn run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - run: yarn run generate
      - run: yarn run test --ci
